# Generated by Django 4.1.7 on 2023-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ftree_Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=100)),
            ],
        ),
    ]
