# Generated by Django 4.1.7 on 2023-04-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftree', '0003_ftree_hierarchy_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftree_hierarchy',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
